
# This file is automatically generated, you probably don't want to edit this

onehotencodingOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "onehotencodingOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            ColumnToSplit = NULL,
            separator = ",", ...) {

            super$initialize(
                package="OneHotEncoding",
                name="onehotencoding",
                requiresData=TRUE,
                ...)

            private$..ColumnToSplit <- jmvcore::OptionVariable$new(
                "ColumnToSplit",
                ColumnToSplit)
            private$..separator <- jmvcore::OptionString$new(
                "separator",
                separator,
                default=",")
            private$..newColumns <- jmvcore::OptionOutput$new(
                "newColumns")

            self$.addOption(private$..ColumnToSplit)
            self$.addOption(private$..separator)
            self$.addOption(private$..newColumns)
        }),
    active = list(
        ColumnToSplit = function() private$..ColumnToSplit$value,
        separator = function() private$..separator$value,
        newColumns = function() private$..newColumns$value),
    private = list(
        ..ColumnToSplit = NA,
        ..separator = NA,
        ..newColumns = NA)
)

onehotencodingResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "onehotencodingResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        newColumns = function() private$.items[["newColumns"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="One Hot Encoding")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Output of Encoding"))
            self$add(jmvcore::Output$new(
                options=options,
                name="newColumns",
                title="New Columns",
                initInRun=TRUE))}))

onehotencodingBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "onehotencodingBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "OneHotEncoding",
                name = "onehotencoding",
                version = c(1,0,0),
                options = options,
                results = onehotencodingResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' One Hot Encoding
#'
#' 
#' @param data .
#' @param ColumnToSplit .
#' @param separator The character used to separate values
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$newColumns} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
onehotencoding <- function(
    data,
    ColumnToSplit,
    separator = ",") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("onehotencoding requires jmvcore to be installed (restart may be required)")

    if ( ! missing(ColumnToSplit)) ColumnToSplit <- jmvcore::resolveQuo(jmvcore::enquo(ColumnToSplit))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(ColumnToSplit), ColumnToSplit, NULL))


    options <- onehotencodingOptions$new(
        ColumnToSplit = ColumnToSplit,
        separator = separator)

    analysis <- onehotencodingClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

